# Generated by Django 4.1.2 on 2022-10-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detailsEndpoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='slack_username',
            new_name='slackUsername',
        ),
    ]
